import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/Providers";
import {Header} from "@/app/components/header/Header";


export const metadata: Metadata = {
  title: "Test task",
  description: "Generated by Andriy Kolos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-Montserrat">
        <Providers>
           <Header />
            {children}
        </Providers>
      </body>
    </html>
  );
}
